package com.hrudyplayz.forcexploseondeath;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;


@Mod(modid = Main.MODID, name = Main.NAME, version = Main.VERSION)
public class Main {

    // We define the mod properties
    public static final String MODID = "forceexploseondeath";
    public static final String NAME = "Force EXP Lose On Death";
    public static final String VERSION = "1.0";
    public static final String DESCRIPTION = "A small mod that allows users to still lose EXP with KeepInventory enabled.";
    public static final String CREDITS = "Henkelmax's Gravestone mod, to let me learn about how death events work.";
    public static final String URL = "";
    public static final boolean LOGO = false;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        // The following overrides the mcmod.info file!
        // Adapted from Jabelar's Magic Beans:
        // https://github.com/jabelar/MagicBeans-1.7.10/blob/e48456397f9c6c27efce18e6b9ad34407e6bc7c7/src/main/java/com/blogspot/jabelarminecraft/magicbeans/MagicBeans.java

        // stops Forge from complaining about missing mcmod.info (in case i forget it).
        event.getModMetadata().autogenerated = false;

        // Mod name
        event.getModMetadata().name = EnumChatFormatting.RED + NAME;

        // Mod version
        event.getModMetadata().version = EnumChatFormatting.BOLD + VERSION;

        // Mod credits
        event.getModMetadata().credits = EnumChatFormatting.BOLD + CREDITS;

        // Author list
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(EnumChatFormatting.RED + "" + EnumChatFormatting.BOLD + "HRudyPlayZ");

        // Mod URL
        event.getModMetadata().url = EnumChatFormatting.GRAY + URL;

        // Mod description
        event.getModMetadata().description = EnumChatFormatting.GRAY + DESCRIPTION;

        // Mod logo
       if (LOGO) event.getModMetadata().logoFile = "title.png";
    }


    @EventHandler
    public void init(FMLInitializationEvent event) {
        MinecraftForge.EVENT_BUS.register(new DeathEvents());
    }
}
